[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.web"

[deploy]
startCommand = "node node_modules/next/dist/bin/next start --hostname 0.0.0.0"
healthcheckPath = "/api/ready"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
